"""Weekly schedule templates — pure."""
from data import TRAINING_TYPES, build_split_schedule

def get_schedule(training_type_name, bmi_cat, fatigue, rl_rec,
                 split_type=None, frequency=None, single_mode=None, focus_muscle=None):
    meta = TRAINING_TYPES.get(training_type_name, {"cat":"hybrid","intensity":3,"emphasis":"variety"})
    cat  = meta["cat"]
    emph = meta["emphasis"]

    # Phase 5: if the user chose a split, build a schedule that MATCHES it
    # (PPL -> push/pull/legs, Upper/Lower -> alternating, etc.). Falls back to
    # the legacy goal-based schedule when no split is given.
    if split_type:
        split_sched = build_split_schedule(split_type, frequency, single_mode,
                                           focus_muscle, total_days=7)
        if split_sched:
            return split_sched, meta

    schedules = {
        "strength":{
            "volume":[("Chest & Triceps",["chest","arms"]),("Back & Biceps",["back","arms"]),
                      ("Legs",["legs"]),("Shoulders & Core",["shoulders","core"]),
                      ("Chest & Back",["chest","back"]),("Arms & Core",["arms","core"]),
                      ("Rest & Recovery",["rest"])],
            "maximal":[("Lower Body",["legs"]),("Upper Push",["chest","shoulders"]),
                       ("Rest & Accessory",["core","rest"]),("Lower Body Hinge",["legs","back"]),
                       ("Upper Pull",["back","arms"]),("Full Body",["chest","legs","core"]),
                       ("Rest & Recovery",["rest"])],
            "power":[("Snatch & Accessory",["olympic","legs"]),("Clean & Jerk",["olympic","back"]),
                     ("Strength Accessory",["legs","shoulders"]),("Technique + Pulls",["olympic","core"]),
                     ("Power Development",["power","legs"]),("Active Recovery",["mobility","recovery"]),
                     ("Rest & Recovery",["rest"])],
            "explosive":[("Lower Power",["power","legs"]),("Upper Power",["power","chest","back"]),
                         ("Plyometric Lower",["plyometric","legs"]),("Plyometric Upper",["plyometric","chest"]),
                         ("Full Power Circuit",["power","plyometric","core"]),("Active Recovery",["mobility"]),
                         ("Rest & Recovery",["rest"])],
            "full_body":[("Event Training A",["strongman","legs"]),("Upper Strength",["chest","back","shoulders"]),
                         ("Event Training B",["strongman","core"]),("Accessory Lower",["legs","core"]),
                         ("Event Training C",["strongman","back"]),("Active Recovery",["recovery","mobility"]),
                         ("Rest & Recovery",["rest"])],
            "static":[("Isometric Upper Push",["isometric","chest"]),("Isometric Upper Pull",["isometric","back"]),
                      ("Isometric Lower",["isometric","legs"]),("Isometric Core",["isometric","core"]),
                      ("Full Body Isometric",["isometric","shoulders","arms"]),("Mobility",["mobility"]),
                      ("Rest & Recovery",["rest"])],
            "aesthetic":[("Chest",["chest"]),("Back",["back"]),("Legs",["legs"]),
                         ("Shoulders",["shoulders"]),("Arms",["arms"]),
                         ("Core & Weak Points",["core","chest","back"]),("Rest & Recovery",["rest"])],
            "balanced":[("Upper Push",["chest","shoulders"]),("Lower Body",["legs"]),
                        ("Upper Pull",["back","arms"]),("Core & Cardio",["core","cardio"]),
                        ("Full Body",["chest","back","legs"]),("Active Recovery",["mobility","recovery"]),
                        ("Rest & Recovery",["rest"])],
        },
        "cardio":{
            "aerobic":[("Steady State Cardio",["cardio"]),("Core + Lower",["core","legs"]),
                       ("Cardio + Mobility",["cardio","mobility"]),("Upper + Cardio",["chest","back","cardio"]),
                       ("Long Cardio",["cardio"]),("Full Body + Stretch",["legs","core","mobility"]),
                       ("Rest & Recovery",["rest"])],
            "anaerobic":[("Anaerobic Intervals",["cardio","power"]),("Strength Lower",["legs"]),
                         ("Sprint Work",["cardio","agility"]),("Strength Upper",["chest","back"]),
                         ("Anaerobic Circuit",["cardio","core","power"]),("Active Recovery",["recovery","mobility"]),
                         ("Rest & Recovery",["rest"])],
        },
        "hiit":{
            "interval":[("HIIT Full Body",["cardio","core"]),("Strength + Power",["chest","back","power"]),
                        ("HIIT Lower",["cardio","legs","plyometric"]),("Upper Strength",["shoulders","arms","back"]),
                        ("MetCon Circuit",["cardio","core","power"]),("Legs + Core",["legs","core"]),
                        ("Rest & Recovery",["rest"])],
            "speed":[("Sprint Intervals",["cardio","agility"]),("Lower Strength",["legs","power"]),
                     ("Sprint Technique",["cardio","agility"]),("Upper Body",["chest","back","shoulders"]),
                     ("Speed Endurance",["cardio","legs"]),("Active Recovery",["recovery","mobility"]),
                     ("Rest & Recovery",["rest"])],
            "metabolic":[("MetCon A",["cardio","legs","core"]),("Upper MetCon",["chest","back","cardio"]),
                         ("Lower MetCon",["legs","cardio","plyometric"]),("Full Body MetCon",["cardio","core","power"]),
                         ("MetCon + Strength",["chest","back","legs"]),("Active Recovery",["recovery","mobility"]),
                         ("Rest & Recovery",["rest"])],
            "full_body":[("Bootcamp Circuit A",["cardio","core","legs"]),("Upper Bootcamp",["chest","back","shoulders"]),
                         ("Bootcamp Circuit B",["cardio","plyometric","core"]),("Lower Bootcamp",["legs","cardio"]),
                         ("Full Bootcamp",["chest","back","legs","core"]),("Active Recovery",["recovery"]),
                         ("Rest & Recovery",["rest"])],
        },
        "endurance":{
            "endurance":[("Long Cardio",["cardio"]),("Leg Endurance",["legs","core"]),
                         ("Mid Cardio + Upper",["cardio","chest","back"]),("Core + Mobility",["core","mobility"]),
                         ("Tempo",["cardio"]),("Full Body Endurance",["legs","core","cardio"]),
                         ("Rest & Recovery",["rest"])],
            "circuit":[("Upper Circuit",["chest","back","shoulders","arms"]),("Lower Circuit",["legs","core"]),
                       ("Full Body Circuit A",["chest","legs","cardio"]),("Core + Cardio",["core","cardio"]),
                       ("Full Body Circuit B",["back","legs","core"]),("Active Recovery",["recovery","mobility"]),
                       ("Rest & Recovery",["rest"])],
        },
        "functional":{
            "movement":[("Hinge Pattern",["back","legs"]),("Push Pattern",["chest","shoulders"]),
                        ("Carry + Core",["core","agility"]),("Pull Pattern",["back","arms"]),
                        ("Squat + Lunge",["legs","core"]),("Rotation + Cardio",["core","cardio"]),
                        ("Rest & Recovery",["rest"])],
            "bodyweight":[("Push Skills",["chest","shoulders","arms"]),("Pull Skills",["back","arms"]),
                          ("Lower Skills",["legs","core"]),("Core Skills",["core","chest"]),
                          ("Full Body Skills",["chest","back","legs","core"]),("Skill + Flex",["mobility","core"]),
                          ("Rest & Recovery",["rest"])],
            "performance":[("Speed + Agility",["agility","legs"]),("Power Development",["power","legs"]),
                           ("Upper Strength",["chest","back","shoulders"]),("Change of Direction",["agility","legs","core"]),
                           ("Sport Power",["power","plyometric","core"]),("Active Recovery",["recovery","mobility"]),
                           ("Rest & Recovery",["rest"])],
            "sport":[("Speed + Power",["agility","power","legs"]),("Upper Strength",["chest","back","shoulders"]),
                     ("Agility Drills",["agility","core"]),("Lower Strength",["legs","core"]),
                     ("Sport Simulation",["cardio","power","agility"]),("Recovery + Mobility",["recovery","mobility"]),
                     ("Rest & Recovery",["rest"])],
            "ballistic":[("KB Lower",["kettlebell","legs"]),("KB Upper Push",["kettlebell","chest","shoulders"]),
                         ("KB Full Body A",["kettlebell","core"]),("KB Upper Pull",["kettlebell","back","arms"]),
                         ("KB Full Body B",["kettlebell","legs","core"]),("Active Recovery",["recovery","mobility"]),
                         ("Rest & Recovery",["rest"])],
            "stability":[("TRX Upper Push",["trx","chest","shoulders"]),("TRX Upper Pull",["trx","back","arms"]),
                         ("TRX Lower",["trx","legs"]),("TRX Core",["trx","core"]),
                         ("TRX Full Body",["trx","chest","back","legs"]),("Mobility + Stretch",["mobility"]),
                         ("Rest & Recovery",["rest"])],
            "speed":[("Speed Drills",["agility","cardio"]),("Lower Power",["legs","power","plyometric"]),
                     ("Agility Circuits",["agility","core"]),("Upper Strength",["chest","back","shoulders"]),
                     ("Speed Endurance",["cardio","agility","legs"]),("Active Recovery",["recovery","mobility"]),
                     ("Rest & Recovery",["rest"])],
            "combat":[("Striking + Footwork",["cardio","agility","core"]),("Upper Strength",["chest","back","shoulders"]),
                      ("Kicking + Agility",["legs","agility","cardio"]),("Grappling Conditioning",["core","back","legs"]),
                      ("Pad Work",["cardio","power","core"]),("Active Recovery",["recovery","mobility"]),
                      ("Rest & Recovery",["rest"])],
        },
        "mobility":{
            "stretch":[("Upper Flexibility",["mobility","chest","shoulders"]),("Lower Flexibility",["mobility","legs"]),
                       ("Spine + Core",["mobility","core"]),("Hip & Groin",["mobility","legs"]),
                       ("Full Body Stretch",["mobility"]),("Restorative Yoga",["yoga","recovery"]),
                       ("Rest & Recovery",["rest"])],
            "joint":[("Hip & Ankle Mobility",["mobility","legs"]),("Shoulder Mobility",["mobility","shoulders"]),
                     ("Spine Mobility",["mobility","core","back"]),("Full Body Mobility",["mobility"]),
                     ("Joint Circuit",["mobility","agility"]),("Yoga Flow",["yoga"]),
                     ("Rest & Recovery",["rest"])],
            "mindful":[("Morning Flow",["yoga","mobility"]),("Strength Yoga",["yoga","core","legs"]),
                       ("Restorative",["yoga","recovery"]),("Balance + Focus",["yoga","core"]),
                       ("Hip Opening Flow",["yoga","legs","mobility"]),("Full Body Flow",["yoga","mobility"]),
                       ("Yoga Nidra",["recovery"])],
            "core_flex":[("Pilates Core",["pilates","core"]),("Pilates Lower",["pilates","legs"]),
                         ("Pilates Upper",["pilates","chest","back"]),("Pilates Full Body",["pilates","core","legs"]),
                         ("Pilates + Mobility",["pilates","mobility"]),("Active Recovery",["recovery"]),
                         ("Rest & Recovery",["rest"])],
            "balance":[("Balance Lower",["legs","isometric","core"]),("Balance Upper",["shoulders","core","isometric"]),
                       ("Proprioception Circuit",["agility","core","legs"]),("Full Body Stability",["isometric","core","legs"]),
                       ("Balance + Mobility",["mobility","isometric"]),("Active Recovery",["recovery"]),
                       ("Rest & Recovery",["rest"])],
            "core":[("Anterior Core",["core"]),("Posterior Core",["core","back"]),
                    ("Lateral Core",["core"]),("Core + Cardio",["core","cardio"]),
                    ("Rotational Core",["core","agility"]),("Core + Mobility",["core","mobility"]),
                    ("Rest & Recovery",["rest"])],
        },
        "hybrid":{
            "variety":[("Cardio + Strength",["cardio","chest","back"]),("Legs + Core",["legs","core"]),
                       ("HIIT + Upper",["cardio","shoulders","arms"]),("Mobility + Lower",["legs","mobility"]),
                       ("Full Body Circuit",["chest","legs","cardio","core"]),("Active Recovery",["recovery","mobility"]),
                       ("Rest & Recovery",["rest"])],
            "aesthetics_function":[("Push + Conditioning",["chest","shoulders","cardio"]),
                                   ("Pull + Conditioning",["back","arms","cardio"]),
                                   ("Leg + Power",["legs","power"]),("Shoulder + Core",["shoulders","core","isometric"]),
                                   ("Full Functional Body",["chest","back","legs","core"]),
                                   ("Active Recovery",["recovery","mobility"]),("Rest & Recovery",["rest"])],
            "resistance":[("Band Upper Push",["chest","shoulders"]),("Band Upper Pull",["back","arms"]),
                          ("Band Lower Body",["legs","core"]),("Band Full Body",["chest","back","legs"]),
                          ("Band Core + Cardio",["core","cardio"]),("Mobility + Stretch",["mobility"]),
                          ("Rest & Recovery",["rest"])],
        },
        "recovery":{
            "rest":[("Light Walk + Foam Roll",["recovery","cardio"]),("Upper Mobility",["mobility","shoulders","chest"]),
                    ("Lower Mobility",["mobility","legs"]),("Breathing + Core",["recovery","core"]),
                    ("Full Body Gentle",["recovery","mobility"]),("Yoga / Stretch",["yoga","recovery"]),
                    ("Rest & Recovery",["rest"])],
            "corrective":[("Movement Screen",["mobility","core"]),("Corrective Upper",["isometric","shoulders","back"]),
                          ("Corrective Lower",["isometric","legs","core"]),("Stability Work",["isometric","core","mobility"]),
                          ("Movement Integration",["mobility","agility","core"]),("Active Recovery",["recovery"]),
                          ("Rest & Recovery",["rest"])],
        },
    }

    cat_schedules = schedules.get(cat, schedules["hybrid"])
    schedule = cat_schedules.get(emph, list(cat_schedules.values())[0])

    # BMI injection handled in build_workout_plan
    return schedule, meta

